"""empty message

Revision ID: ebf1a5fead06
Revises: cd15df6be6f4
Create Date: 2023-12-23 21:04:21.275860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf1a5fead06'
down_revision = 'cd15df6be6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite__people')
    op.drop_table('favorite__planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite__planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite__planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite__planets_pkey')
    )
    op.create_table('favorite__people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='favorite__people_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite__people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite__people_pkey')
    )
    # ### end Alembic commands ###
